---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- directory: Applications/PetPortalHosts

---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/PetPortalHosts/servers
  type: udm.Application

---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: !format Applications/PetPortalHosts/servers/%version%
  type: udm.ProvisioningPackage
  templates:
  - name: sshHost
    type: template.overthere.SshHost
    instanceName: '{{project}}/TEST/{{%outputVariables.ec2_server_public_dns%}}'
    childTemplates:
    - name: tomcat
      type: template.tomcat.Server
      childTemplates:
      - name: webapps
        type: template.tomcat.VirtualHost
      home: /var/lib/tomcat
      startCommand: systemctl start tomcat
      stopCommand: systemctl stop tomcat
      statusCommand: systemctl status tomcat
      startWaitTime: "10"
      stopWaitTime: "10"
    - name: apache
      type: template.www.ApacheHttpdServer
      startCommand: systemctl start httpd
      stopCommand: systemctl stop httpd
      restartCommand: systemctl restart httpd
      defaultDocumentRoot: /var/www/html
      configurationFragmentDirectory: /etc/httpd/httpd.d
    os: UNIX
    address: '{{%outputVariables.ec2_server_public_dns%}}'
    username: ec2-user
    privateKeyFile: /opt/xebialabs/xl-deploy-server/conf/rbroker-us1.pem
  deployables:
  - name: servers
    type: terraform.Module
    boundTemplates:
    - !format Applications/PetPortalHosts/servers/%version%/sshHost
    preScannedPlaceholders: true
    placeholders:
    - AWSRegion
    - AWS_SECRET_KEY
    - AWS_ACCESS_KEY
    fileEncodings:
      ".+\\.properties": ISO-8859-1
    environmentPath: '{{PROJECT}}/{{PROJECT}}-DEV'
    automaticDictionary: "true"
    dictionaryPath: '{{PROJECT}}-dic'
    generateCIsFromResources: "true"
    inputVariables:
      project: rrb-aws
    file: !file "artifacts/aws.ec2_instance.zip"
