name: Build-PetPortalHosts
on: [push]
jobs:
  build-pet-portal-hosts-version:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        env:
          XLD_USER: ${{ secrets.XLD_USER }}
          XLD_PASSWD: ${{ secrets.XLD_PASSWD }}
      - uses: actions/checkout@v2
      - run: ./build.sh
