name: Build-PetPortalHosts
on: [push]
jobs:
  build-pet-portal-hosts-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        env:
          XLD_USER: ${{ secrets.XLD_USER }}
          XLD_PASSWD: ${{ secrets.XLD_PASSWD }}
        run: ./build.sh
